version = 0.1
[dev.deploy.parameters]
stack_name = "tips-dev"
resolve_s3 = true
s3_prefix = "tips-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "LambdaFunctionName=\"tips-lambda-processrequest-dev\" S3BucketName=\"tips-s3-uploads-dev\" APIGatewayName=\"tips-api-gateway-dev\""
image_repositories = []
